# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FunhiPrototype2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Gifu'
  # Pods for FunhiPrototype2

  target 'FunhiPrototype2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FunhiPrototype2UITests' do
    # Pods for testing
  end

end
