# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LastSecond_For_Scenario' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Gifu'
  # Pods for LastSecond_For_Scenario

  target 'LastSecond_For_ScenarioTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LastSecond_For_ScenarioUITests' do
    # Pods for testing
  end

end
